vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix:         /public/uploads/image
            upload_destination: '%kernel.project_dir%/public/uploads/image'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
